### ISSUE TITLE
Please add a license to this project

### ISSUE THREAD

**Issue by sirex** [goodtune/django-prototype#1]
I would like to contribute to this project but there is no licence specified, so I'm not sure if this project is open for contributions or not?

**Comment by goodtune** [comment]
I have not worked on this in some time but would welcome contributions.

**Comment by sirex** [comment]
I see that you added a public domain licence. Usually I use one of GPL licenceses, just to protect my work from falling into wrong hands. Public domain licence means, that no one is asked to contribute back to this project.

I'm ok with public domain, but just letting you know, that public domain is quite risky thing for open source projects.
